/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	appsv1 "dt-runner/apis/apps/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCis implements CiInterface
type FakeCis struct {
	Fake *FakeAppsV1
}

var cisResource = schema.GroupVersionResource{Group: "apps.dtwave.com", Version: "v1", Resource: "cis"}

var cisKind = schema.GroupVersionKind{Group: "apps.dtwave.com", Version: "v1", Kind: "Ci"}

// Get takes name of the ci, and returns the corresponding ci object, and an error if there is any.
func (c *FakeCis) Get(name string, options v1.GetOptions) (result *appsv1.Ci, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(cisResource, name), &appsv1.Ci{})
	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Ci), err
}

// List takes label and field selectors, and returns the list of Cis that match those selectors.
func (c *FakeCis) List(opts v1.ListOptions) (result *appsv1.CiList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(cisResource, cisKind, opts), &appsv1.CiList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appsv1.CiList{ListMeta: obj.(*appsv1.CiList).ListMeta}
	for _, item := range obj.(*appsv1.CiList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cis.
func (c *FakeCis) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(cisResource, opts))
}

// Create takes the representation of a ci and creates it.  Returns the server's representation of the ci, and an error, if there is any.
func (c *FakeCis) Create(ci *appsv1.Ci) (result *appsv1.Ci, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(cisResource, ci), &appsv1.Ci{})
	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Ci), err
}

// Update takes the representation of a ci and updates it. Returns the server's representation of the ci, and an error, if there is any.
func (c *FakeCis) Update(ci *appsv1.Ci) (result *appsv1.Ci, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(cisResource, ci), &appsv1.Ci{})
	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Ci), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCis) UpdateStatus(ci *appsv1.Ci) (*appsv1.Ci, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(cisResource, "status", ci), &appsv1.Ci{})
	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Ci), err
}

// Delete takes name of the ci and deletes it. Returns an error if one occurs.
func (c *FakeCis) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(cisResource, name), &appsv1.Ci{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCis) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(cisResource, listOptions)

	_, err := c.Fake.Invokes(action, &appsv1.CiList{})
	return err
}

// Patch applies the patch and returns the patched ci.
func (c *FakeCis) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *appsv1.Ci, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(cisResource, name, data, subresources...), &appsv1.Ci{})
	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Ci), err
}
