/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "dt-runner/apis/apps/v1"
	scheme "dt-runner/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CisGetter has a method to return a CiInterface.
// A group's client should implement this interface.
type CisGetter interface {
	Cis() CiInterface
}

// CiInterface has methods to work with Ci resources.
type CiInterface interface {
	Create(*v1.Ci) (*v1.Ci, error)
	Update(*v1.Ci) (*v1.Ci, error)
	UpdateStatus(*v1.Ci) (*v1.Ci, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Ci, error)
	List(opts metav1.ListOptions) (*v1.CiList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ci, err error)
	CiExpansion
}

// cis implements CiInterface
type cis struct {
	client rest.Interface
}

// newCis returns a Cis
func newCis(c *AppsV1Client) *cis {
	return &cis{
		client: c.RESTClient(),
	}
}

// Get takes name of the ci, and returns the corresponding ci object, and an error if there is any.
func (c *cis) Get(name string, options metav1.GetOptions) (result *v1.Ci, err error) {
	result = &v1.Ci{}
	err = c.client.Get().
		Resource("cis").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Cis that match those selectors.
func (c *cis) List(opts metav1.ListOptions) (result *v1.CiList, err error) {
	result = &v1.CiList{}
	err = c.client.Get().
		Resource("cis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cis.
func (c *cis) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("cis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a ci and creates it.  Returns the server's representation of the ci, and an error, if there is any.
func (c *cis) Create(ci *v1.Ci) (result *v1.Ci, err error) {
	result = &v1.Ci{}
	err = c.client.Post().
		Resource("cis").
		Body(ci).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ci and updates it. Returns the server's representation of the ci, and an error, if there is any.
func (c *cis) Update(ci *v1.Ci) (result *v1.Ci, err error) {
	result = &v1.Ci{}
	err = c.client.Put().
		Resource("cis").
		Name(ci.Name).
		Body(ci).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cis) UpdateStatus(ci *v1.Ci) (result *v1.Ci, err error) {
	result = &v1.Ci{}
	err = c.client.Put().
		Resource("cis").
		Name(ci.Name).
		SubResource("status").
		Body(ci).
		Do().
		Into(result)
	return
}

// Delete takes name of the ci and deletes it. Returns an error if one occurs.
func (c *cis) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("cis").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cis) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Resource("cis").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ci.
func (c *cis) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ci, err error) {
	result = &v1.Ci{}
	err = c.client.Patch(pt).
		Resource("cis").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
