/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "dt-runner/apis/apps/v1"
	scheme "dt-runner/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ModelsGetter has a method to return a ModelInterface.
// A group's client should implement this interface.
type ModelsGetter interface {
	Models() ModelInterface
}

// ModelInterface has methods to work with Model resources.
type ModelInterface interface {
	Create(*v1.Model) (*v1.Model, error)
	Update(*v1.Model) (*v1.Model, error)
	UpdateStatus(*v1.Model) (*v1.Model, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Model, error)
	List(opts metav1.ListOptions) (*v1.ModelList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Model, err error)
	ModelExpansion
}

// models implements ModelInterface
type models struct {
	client rest.Interface
}

// newModels returns a Models
func newModels(c *AppsV1Client) *models {
	return &models{
		client: c.RESTClient(),
	}
}

// Get takes name of the model, and returns the corresponding model object, and an error if there is any.
func (c *models) Get(name string, options metav1.GetOptions) (result *v1.Model, err error) {
	result = &v1.Model{}
	err = c.client.Get().
		Resource("models").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Models that match those selectors.
func (c *models) List(opts metav1.ListOptions) (result *v1.ModelList, err error) {
	result = &v1.ModelList{}
	err = c.client.Get().
		Resource("models").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested models.
func (c *models) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("models").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a model and creates it.  Returns the server's representation of the model, and an error, if there is any.
func (c *models) Create(model *v1.Model) (result *v1.Model, err error) {
	result = &v1.Model{}
	err = c.client.Post().
		Resource("models").
		Body(model).
		Do().
		Into(result)
	return
}

// Update takes the representation of a model and updates it. Returns the server's representation of the model, and an error, if there is any.
func (c *models) Update(model *v1.Model) (result *v1.Model, err error) {
	result = &v1.Model{}
	err = c.client.Put().
		Resource("models").
		Name(model.Name).
		Body(model).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *models) UpdateStatus(model *v1.Model) (result *v1.Model, err error) {
	result = &v1.Model{}
	err = c.client.Put().
		Resource("models").
		Name(model.Name).
		SubResource("status").
		Body(model).
		Do().
		Into(result)
	return
}

// Delete takes name of the model and deletes it. Returns an error if one occurs.
func (c *models) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("models").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *models) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Resource("models").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched model.
func (c *models) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Model, err error) {
	result = &v1.Model{}
	err = c.client.Patch(pt).
		Resource("models").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
